### PR TITLE
implement Rotate={0,1,2,3} in the GLES codepath

### PR DESCRIPTION
**Pull request by krnlyng**

### CODE REVIEW

**Comment by littleguy77** [comment]
We have had reports on Android of numerous regressions in video-rice and I tracked it down to this commit.  Most of the reports describe "garbage" artifacts.  A more benign example is this one, where the sparkles are rendered outside the letter-boxed area at the top and bottom (I have personally verified this):
super_mario_64-006

Here is a sampling of reports, I'm not sure how many are due to this commit, but when I revert this commit I hear new reports like "everything is fixed!" etc.:
http://www.paulscode.com/forum/index.php?topic=1818.msg14004#msg14004
http://www.paulscode.com/forum/index.php?topic=1818.msg14117#msg14117
http://www.paulscode.com/forum/index.php?topic=1818.msg14124#msg14124
http://www.paulscode.com/forum/index.php?topic=1818.msg14139#msg14139
http://www.paulscode.com/forum/index.php?topic=1818.msg14140#msg14140

Issues caused by this commit have also been discussed before in issues #24 and #25.

Given that
 - @Narann has a big refactoring/rewrite pending, and
 - @Gillou68310 describes at least a partial fix at https://github.com/Gillou68310/mupen64plus-video-rice/commit/c3c17c82c424b89f60e8cd18ada62a82681d5433

I wonder what is the best way to proceed?  Is this fixable?  Is the only real solution to revert? :(  Should we just wait until @Narann's PR is ready?

**Comment by Narann** [comment]
Thanks for report @littleguy77. As I said in #25 the purposed way has some side effect. Remove it manually (for test) should not be so complicate actually. Do you think you could remove those few lines and test again? https://github.com/krnlyng/mupen64plus-video-rice/commit/e9ef968bd5961181099072b710e1c200f88106f6

**Comment by littleguy77** [comment]
I git bisected to identify this commit.  Then I reset to head revision and reverted this commit, tested, and posted to paulscode forum.  You can see the branch in https://github.com/mupen64plus-ae.

My question is now that it's identified and confirmed, how do you want me to proceed... Submitting a PR that simply reverts may be too extreme.

**Comment by Narann** [comment]
I don't understand:

> Then I reset to head revision and reverted this commit, tested, and posted to paulscode forum.

Ok, but as you don't provide a link to your post I can't guess if you fixed the problem or not.

So, can you confirm manually remove https://github.com/krnlyng/mupen64plus-video-rice/commit/e9ef968bd5961181099072b710e1c200f88106f6 fix the problem?

Why removing this PR seems too extreme?
1) The current way to rotate only affect one part of the color combiner (the 1/2 cycle). So other modes still don't rotate anything.
2) The provided _fix_ actually blow the code to every stage of the color combiner to do the transform. I think it's not "the way it should be done".

So [I removed this](https://github.com/mupen64plus/mupen64plus-video-rice/issues/25#issuecomment-67919925) from my repo (and I forgot it was also in the main repo).

That's why I think removing this PR from the code is not such a bad idea, specially if it had such side effect.

So:
* Could you confirm you fixed the problem removing https://github.com/krnlyng/mupen64plus-video-rice/commit/e9ef968bd5961181099072b710e1c200f88106f6.
* If so, could you do a PR removing this PR? :)

**Comment by littleguy77** [comment]
Maybe there's a language barrier?  I tried to say twice now, I already did remove commit e9ef968 (using `git revert`) and confirmed that it does indeed fix the regressions.  Here is the specific commit where I did it:

**Comment by littleguy77** [comment]
I will submit the PR now to revert this commit.

**Comment by Narann** [comment]
> Maybe there's a language barrier?

Haha maybe. I understood what you say _imply_ the problem was fixed but as code is quite fragile I prefer explicit words. ^^

Merged.

**Pull request merged**
