### PR TITLE
Fix GLES regression...

### PR DESCRIPTION
**Pull request by gizmo98**
...introduced with https://github.com/mupen64plus/mupen64plus-video-rice/pull/52

### CODE REVIEW

**Comment by Narann** [comment]
I'm not sure you actually "fix" the problem, just revert back to it initial state (which was not good IMHO). I think the problem came form https://github.com/mupen64plus/mupen64plus-video-rice/blob/master/src/OGLExtensions.cpp#L22.

I would have replaced `#include <SDL_opengl.h>` by `#include "osal_opengl.h"` in `OGLExtensions.cpp` instead.

**Comment by gizmo98** [comment]
We only need Extensions if USE_GLES is not defined. I added "#ifndef USE_GLES" so the code will not be used if USE_GLES is defined.

Any reason the travis build timed out?

**Comment by Narann** [comment]
> We only need Extensions if USE_GLES is not defined.

I'm surprised. Are you sure? OGLExtension.cpp define function pointers to _pgl_ functions used everywhere.

**Comment by gizmo98** [comment]
OGLExtensions.h is only included in OGLRender.cpp. OGLRender.cpp has already #ifndef USE_GLES around this include. Don't know how this header file can be necessary if it is not included?!

**Comment by richard42** [comment]
Narann, do you have any suggestions for a better fix for this?  We need to resolve this before the release.

**Comment by Narann** [comment]
Oups! My bad! :)

**Pull request merged**
